### ISSUE TITLE
Linux Neko install

### ISSUE THREAD

**Issue by joekinley** [dpeek/hvm#6]
When I do "hvm use neko latest" on linux I get the following output:

```
bash: http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/neko/linux64/neko_latest.tar.gz: No such file or directory
downloading http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/neko/mac/neko_latest.tar.gz
```

Which results in problems, as the mac binaries don't work on linux.
Workaround: Had to manually download the file (from the SAME location it stated to not find), and put it in the folder.

**Comment by dpeek** [comment]
Thanks for the report, I think this is fixed now.
