### ISSUE TITLE
mac os x el capitan error

### ISSUE THREAD

**Issue by midorikocak** [dpeek/hvm#8]
mtkocak@Midori-MacBook-Pro ~/s/my5-mui> source ~/.profile
'case' builtin not inside of switch block
~/.hvm/hvm.sh (line 25):    case $PLATFORM in
                            ^
from sourcing file ~/.hvm/hvm.sh
    called on line 1 of file ~/.profile

from sourcing file ~/.profile
    called on standard input

source: Error while reading file '/Users/mtkocak/.hvm/hvm.sh'

**Comment by dpeek** [comment]
Not sure about this error, but I've tested now on el capitan and things seem to be working. We now install to /usr/local/bin instead of /usr/bin so it might be worth reinstalling.
